# Generated by Django 3.1.4 on 2021-02-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Running',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('distant', models.IntegerField()),
                ('runner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runner.runner')),
            ],
        ),
    ]
