# Generated by Django 3.1.4 on 2021-02-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_auto_20210202_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='running',
            name='date',
            field=models.CharField(default=models.IntegerField(), max_length=10),
        ),
        migrations.AlterField(
            model_name='running',
            name='distant',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
