# Generated by Django 3.1.4 on 2021-02-13 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0005_auto_20210213_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='running',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 2, 13, 14, 13, 28, 683388, tzinfo=utc), max_length=10),
        ),
    ]
