# Generated by Django 3.1.4 on 2021-02-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0006_auto_20210213_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='running',
            name='date',
            field=models.CharField(default='02-19', max_length=10),
        ),
    ]
